codecov:
  bot: "kevinkooyizen"

coverage:
  status:
    project:
      screens:
        flags:
          - screens
      services:
        flags:
          - services

ignore:
  - "lib/src/**/*.g.dart"

# adding Flags to your `layout` configuration to show up in the PR comment
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null

flags:
  screens:
    # only include files in the screens folder
    paths:
      - lib/screens
    carryforward: true
  services:
    # only include files in the services folder
    paths:
      - lib/services
    carryforward: true
