codecov:
  bot: "kevinkooyizen"

coverage:
  status:
    project:
      default: off
      screens:
        target: 100%
        paths: lib/screens/
      services:
        target: 100%
        paths: lib/services/
      utilities:
        target: 100%
        paths: lib/utilities/

ignore:
  - "lib/src/**/*.g.dart"

# adding Flags to your `layout` configuration to show up in the PR comment
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null

# Path fixing for when coverage report doesn't match CI build path
# https://docs.codecov.com/docs/fixing-paths
fixes:
  - "/home/circleci/::"
  - "/root/::"

flags:
  screens:
    # only include files in the screens folder
    paths:
      - lib/screens/
    carryforward: false
  services:
    # only include files in the services folder
    paths:
      - lib/services/
    carryforward: false
  utilities:
    # only include files in the utilities folder
    paths:
      - lib/utilities/
    carryforward: false
