coverage:
  status:
    project:
      screens:
        flags:
          - screens
      services:
        flags:
          - services
      utilities:
        flags:
          - utilities
      widgets:
        flags:
          - widgets

ignore:
  - "lib/src/**/*.g.dart"

flags:
  screens:
    # only include files in the screens folder
    paths:
      - lib/screens
    carryforward: true
  services:
    # only include files in the services folder
    paths:
      - lib/services
    carryforward: true
  utilities:
    # only include files in the utilities folder
    paths:
      - lib/utilities
    carryforward: true
  widgets:
    # only include files in the widgets folder
    paths:
      - lib/widgets
    carryforward: true
