coverage:
  status:
    project:
      screens:
        flags:
          - screens
      services:
        flags:
          - services

ignore:
  - "lib/src/**/*.g.dart"

flags:
  screens:
    # only include files in the screens folder
    paths:
      - lib/screens
    carryforward: true
  services:
    # only include files in the services folder
    paths:
      - lib/services
    carryforward: true
