# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  flutter: circleci/flutter@1.0.0
  gcp-cli: circleci/gcp-cli@2.2.0
  codecov: codecov/codecov@3.2.2

executors:
  cirrusci-flutter:
    docker:
      - image: cirrusci/flutter:2.8.0
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"
      GRADLE_OPTS: '-Xmx1024m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'

jobs:
  checkout-and-setup:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  flutter-widget-test:
    executor: cirrusci-flutter
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run: flutter pub global activate junitreport
      - run: mkdir -p test-results
      - run:
          name: Run unit tests
          command: flutter test --machine | ~/.pub-cache/bin/tojunit --output test-results/flutter.xml
      - store_test_results:
          path: test-results
  code-coverage:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ./
      - codecov/upload:
          flags: screens
          xtra_args: -v -Z
      - codecov/upload:
          flags: services,utilities
          xtra_args: -v -Z
      - codecov/upload:
          flags: utilities
          xtra_args: -v -Z
#      - run: sudo apt update
#      - run: sudo apt install gpg-agent -y
#      - run: flutter test --coverage
  flutter-analyze:
    executor: cirrusci-flutter
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run: flutter analyze

workflows:
  version: 2.1
  development-workflow:
    jobs:
      - checkout-and-setup:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
                - /release\/.*/
                - /temp\/.*/
                - /master/
      - flutter-widget-test:
          requires:
            - checkout-and-setup
      - code-coverage:
          requires:
            - checkout-and-setup
      - flutter-analyze:
          requires:
            - checkout-and-setup
